Landing Page
radioactivetoyhq/rubyonrails-website pull request #1
Opened 2023-05-22 01:12 UTC by weepotty

# Description

This is the landing page. As far as possible I've tried to use pre-existing CSS classes.

Fixes # (issue)
https://3.basecamp.com/5349022/buckets/32784806/todos/6162939797

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- On desktop
<img width="1693" alt="Screenshot 2023-05-22 at 9 10 29 AM" src="https://github.com/radioactivetoyhq/rubyonrails-website/assets/99415923/cb3f8a5a-3243-41a3-af1e-1c40caf33ea4">
<img width="1702" alt="Screenshot 2023-05-22 at 9 10 39 AM" src="https://github.com/radioactivetoyhq/rubyonrails-website/assets/99415

- On mobile screen
<img width="477" alt="Screenshot 2023-05-22 at 9 10 50 AM" src="https://github.com/radioactivetoyhq/rubyonrails-website/assets/99415923/65fb9a20-3f15-4c8b-83c4-b90f39fc3866">
923/2a2caf8f-2bff-45c6-a0f3-1dfbb993781e">

<img width="525" alt="Screenshot 2023-05-22 at 9 10 44 AM" src="https://github.com/radioactivetoyhq/rubyonrails-website/assets/99415923/47b907a7-bba6-410c-bc3a-7ba8682623c1">

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added proof(eg. screenshots) that prove my fix is effective or that my feature works

2023-05-22 20:17 UTC, ayushn21 requested changes
Fantastic stuff @weepotty, seriously good job! 

I've left a handful of comments, some purely advisory but I think we're 90% of the way there. I'll take another look tomorrow because I'm half asleep so there's every change I've missed something 😂 

Before we merge, it's worth cleaning up the commits so the commit history is always sequential and logical. Here's how I usually do this on other projects:

```shell
$ git fetch
$ git reset --mixed origin/world
# This will reset the state of your current branch to origin/world and all your changes will be in the working copy
# Re-commit your changes in a logical order. For eg: Create world layout, Add amsterdam skyline SVG, Create world landing page ..... something along those lines .... that way, someone reading the commit history has a clear picture of the sequence of changes and there are no "work in progress" commits. Make sense?

$ git push --force
```

The above is a destructive change and hence risky ... if you're unsure about what you're doing, ping me, happy to virtually "look over your shoulder" while you do it to ensure you don't lose your work.

2023-05-22 20:17 UTC, ayushn21 commented on world/index.html
> +    <a href="#skyline"
This isn't a hard and fast rule, but I think putting the `>` for a tag on a new line is less readable. I prefer this formatting:

```
<a href="#skyline">
  <img src="../assets/images/logo-railsworld.svg" alt="rails world logo" />
</a>
```

This is personal preference so this is purely advisory, but I'm curious about what you think? For consistency with the rest of the project, I reckon it's worth changing though.

If you do change it, please change it everywhere in the file.

2023-05-22 20:17 UTC, ayushn21 commented on world/index.html
> +      ><img src="../assets/images/logo-railsworld.svg" alt="rails world logo"
Another purely advisory ... I shouldn't even be mentioning this it's so unbelievably minor but my OCD is making me at least leave a comment :D 

I think we should capitalise the alt text: "Rails World Logo".

(One hell of a nitpick, I know, sorry!)

2023-05-22 20:17 UTC, ayushn21 commented on world/index.html
> +        <strong>Location:</strong> Beurs van Berlage, Amsterdam, NL
I wonder if it's worth linking this to Google Maps so folks can conveniently see where the venue is?

2023-05-22 20:17 UTC, ayushn21 commented on _sass/modules/_world.scss
> +  align-items:end;
Please ensure there's 1 space between the key and value of the style rule for consistency :)

2023-05-22 20:17 UTC, ayushn21 commented on world/index.html
> +  <section class="landing__top common-background--white">
Love the use of `<section>` rather than `<div>` everywhere on this page, good choice!

2023-05-22 20:17 UTC, ayushn21 commented on world/index.html
> +        href="https://www.papercall.io/rails-world-2023"
Let's add `target="_blank"` here so the link opens in a new tab.

2023-05-23 01:16 UTC, weepotty commented
thanks 🙏🏻 btw this PR preview feature is great!

2023-05-23 02:30 UTC, weepotty commented
Thanks for all the feedback Ayush, I've made the changes suggested - you can have a look at the code and let me know if you spot anything else. Whenever we are happy to merge, I'll clean up the commits.

2023-05-23 10:57 UTC, ayushn21 approved these changes
Awesome ... looks good to me 👏  .... @AmandaPerino please take a peek if you've got any further feedback ... from my end this is good to go ... I'll merge it once you clean the commit history @weepotty 👍

2023-05-23 11:48 UTC, AmandaPerino commented
> Awesome ... looks good to me 👏 .... @AmandaPerino please take a peek if you've got any further feedback ... from my end this is good to go ... I'll merge it once you clean the commit history @weepotty 👍

Looks great! Go for it!

2023-05-23 11:52 UTC, AmandaPerino commented
Are you all okay with the landing page **not** having the disclaimer? It should definitely be on the full website. 

"This website was created by <Dev Name & Link> & <Dev Name & Link> , junior developers from the Rails community.
It was commissioned by the Rails Foundation, designed by <Designer Name & Link>,  and created under the mentorship of <Mentor Name & Link>."

2023-05-23 11:55 UTC, ayushn21 commented
I'm not fussed about it for the landing page since it's temporary, but happy to have it in there if @weepotty and Mohamed would prefer.

2023-05-23 12:08 UTC, AmandaPerino commented
Sorry one more thing - can you please add a banner to the homepage which links to /world with the text: **Join us for the first Rails World this October in Amsterdam. Tickets on sale soon.** If a banner is too much to add right now, perhaps just an **Events** tab in the navbar?

2023-05-23 13:50 UTC, weepotty commented
> I reckon a banner is pretty straightforward ... best not to upset the balance of the navbar in my opinion ... also the navbar is hidden away in a burger menu on mobile, whereas a banner will always be visible so definitely the way to go in my opinion!
> 
> I'd probably put it right at the top of the page, above the navbar, flush with the top of the viewport ... What do you think?
> 
> @weepotty do you want to take a stab at it? Please do it in a separate PR though.

Sure I'll have a go at the banner tomorrow.

2023-05-23 14:36 UTC, AmandaPerino commented
@weepotty #DBD3D5 (the pale pink) with black text. To match this box please:
<img width="427" alt="Screenshot 2023-05-23 at 16 35 24" src="https://github.com/radioactivetoyhq/rubyonrails-website/assets/58528404/a0996bf3-51ed-479c-a3f2-3b6332ba33ee">

@ayushn21 Are we setting the landing page live today already? I'd like to update the board.

2023-05-23 14:42 UTC, ayushn21 commented
@weepotty I think you should be able to re-use the existing `common-button` and `common-button--version` classes to match the button styling.

@AmandaPerino Nope, I thought we could go live once we have the banner and social image ready as well. I'll merge this PR once we fix the button but that won't push it live .... we'll need to create a PR into the main repository for that which I think is worth doing once we have everything in place. Is that alright?

2023-05-24 11:24 UTC, merged